# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d09b3431d16b40aa7834a5701f4353697a6f3a2721d8d0c0aaabf6de5c8b631b2117a8e3edaa9a8d41f0eaf94de7181a922a4930845bde51fab3f154ebe12814

test:
  secret_key_base: 8410ed6bd3cf5166752f51f2db303dc571c58a581f9a12aa764b4343f771d8e73461f653d5ed48d4abbc570b823ade395a9b6fc7f399136c3167175831e4486f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
